In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from sklearn.preprocessing import *
from sklearn.feature_selection import *
from sklearn.decomposition import *
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import ExtraTreesClassifier

Подготовка данных

In [ ]:
df_w = pd.read_csv("D:\data\winequality-white.csv", sep=";")
df_w.insert(0, 'color', 'white')
df_w.columns = df.columns.str.replace(" ", "_")

df_r = pd.read_csv("D:\data\winequality-red.csv", sep=";")
df_r.insert(0, 'color', 'red')
df_r.columns = df.columns.str.replace(" ", "_")

df = pd.concat([df_w, df_r])
df

color  fixed_acidity  volatile_acidity  citric_acid  residual_sugar  \
0     white            7.0             0.270         0.36            20.7   
1     white            6.3             0.300         0.34             1.6   
2     white            8.1             0.280         0.40             6.9   
3     white            7.2             0.230         0.32             8.5   
4     white            7.2             0.230         0.32             8.5   
...     ...            ...               ...          ...             ...   
1594    red            6.2             0.600         0.08             2.0   
1595    red            5.9             0.550         0.10             2.2   
1596    red            6.3             0.510         0.13             2.3   
1597    red            5.9             0.645         0.12             2.0   
1598    red            6.0             0.310         0.47             3.6   

      chlorides  free_sulfur_dioxide  total_sulfur_dioxide  density    pH  \
0         0.045                 45.0                 170.0  1.00100  3.00   
1         0.049                 14.0                 132.0  0.99400  3.30   
2         0.050                 30.0                  97.0  0.99510  3.26   
3         0.058                 47.0                 186.0  0.99560  3.19   
4         0.058                 47.0                 186.0  0.99560  3.19   
...         ...                  ...                   ...      ...   ...   
1594      0.090                 32.0                  44.0  0.99490  3.45   
1595      0.062                 39.0                  51.0  0.99512  3.52   
1596      0.076                 29.0                  40.0  0.99574  3.42   
1597      0.075                 32.0                  44.0  0.99547  3.57   
1598      0.067                 18.0                  42.0  0.99549  3.39   

      sulphates  alcohol  quality  
0          0.45      8.8        6  
1          0.49      9.5        6  
2          0.44     10.1        6  
3          0.40      9.9        6  
4          0.40      9.9        6  
...         ...      ...      ...  
1594       0.58     10.5        5  
1595       0.76     11.2        6  
1596       0.75     11.0        6  
1597       0.71     10.2        5  
1598       0.66     11.0        6  

[6497 rows x 13 columns]

In [ ]:
arr = df.values
arr

array([['white', 7.0, 0.27, ..., 0.45, 8.8, 6],
       ['white', 6.3, 0.3, ..., 0.49, 9.5, 6],
       ['white', 8.1, 0.28, ..., 0.44, 10.1, 6],
       ...,
       ['red', 6.3, 0.51, ..., 0.75, 11.0, 6],
       ['red', 5.9, 0.645, ..., 0.71, 10.2, 5],
       ['red', 6.0, 0.31, ..., 0.66, 11.0, 6]], dtype=object)

In [ ]:
X = arr[:, 1:-2]
X = X.astype('float')
X

array([[7.   , 0.27 , 0.36 , ..., 1.001, 3.   , 0.45 ],
       [6.3  , 0.3  , 0.34 , ..., 0.994, 3.3  , 0.49 ],
       [8.1  , 0.28 , 0.4  , ..., 0.995, 3.26 , 0.44 ],
       ...,
       [6.3  , 0.51 , 0.13 , ..., 0.996, 3.42 , 0.75 ],
       [5.9  , 0.645, 0.12 , ..., 0.995, 3.57 , 0.71 ],
       [6.   , 0.31 , 0.47 , ..., 0.995, 3.39 , 0.66 ]])

In [ ]:
Y = arr[:,-1]
Y = Y.astype('int')
Y

array([6, 6, 6, ..., 6, 5, 6])

X - численные параметры вина (крепкость, количество сахаров, плотность и т.д.)
Y - оценка вина 

In [ ]:
np.set_printoptions(3)

In [ ]:
min_max_scaler = MinMaxScaler()
min_max_scaler.fit_transform(X)

array([[0.264, 0.127, 0.217, ..., 0.268, 0.217, 0.129],
       [0.207, 0.147, 0.205, ..., 0.133, 0.45 , 0.152],
       [0.355, 0.133, 0.241, ..., 0.154, 0.419, 0.124],
       ...,
       [0.207, 0.287, 0.078, ..., 0.166, 0.543, 0.298],
       [0.174, 0.377, 0.072, ..., 0.161, 0.659, 0.275],
       [0.182, 0.153, 0.283, ..., 0.162, 0.519, 0.247]])

In [ ]:
st_scaler = StandardScaler()
st_scaler.fit(X)
st_scaler.transform(X)

array([[-0.166, -0.423,  0.285, ...,  2.102, -1.359, -0.546],
       [-0.706, -0.241,  0.147, ..., -0.232,  0.507, -0.277],
       [ 0.682, -0.362,  0.56 , ...,  0.135,  0.258, -0.613],
       ...,
       [-0.706,  1.035, -1.298, ...,  0.348,  1.253,  1.47 ],
       [-1.015,  1.855, -1.367, ...,  0.258,  2.186,  1.201],
       [-0.937, -0.18 ,  1.042, ...,  0.265,  1.067,  0.865]])

In [ ]:
norm_scaler = Normalizer()
norm_scaler.fit(X)
norm_scaler.transform(X)

array([[0.039, 0.002, 0.002, ..., 0.006, 0.017, 0.003],
       [0.047, 0.002, 0.003, ..., 0.007, 0.025, 0.004],
       [0.079, 0.003, 0.004, ..., 0.01 , 0.032, 0.004],
       ...,
       [0.126, 0.01 , 0.003, ..., 0.02 , 0.068, 0.015],
       [0.107, 0.012, 0.002, ..., 0.018, 0.065, 0.013],
       [0.129, 0.007, 0.01 , ..., 0.021, 0.073, 0.014]])

In [ ]:
binarizer = Binarizer(threshold=0)
binarizer.fit(st_scaler.transform(X))
binarizer.transform(st_scaler.transform(X))

array([[0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 1., 1., 0.],
       ...,
       [0., 1., 0., ..., 1., 1., 1.],
       [0., 1., 0., ..., 1., 1., 1.],
       [0., 0., 1., ..., 1., 1., 1.]])

In [ ]:
select_k = SelectKBest(score_func=f_classif, k=4)
select_k.fit(X, Y)
select_k.scores_

array([  8.004,  96.674,   9.31 ,   9.111,  50.85 ,  14.939,   7.716,
       136.951,   2.021,   4.326])

In [ ]:
select_k.transform(X)

array([[ 0.27 ,  0.045, 45.   ,  1.001],
       [ 0.3  ,  0.049, 14.   ,  0.994],
       [ 0.28 ,  0.05 , 30.   ,  0.995],
       ...,
       [ 0.51 ,  0.076, 29.   ,  0.996],
       [ 0.645,  0.075, 32.   ,  0.995],
       [ 0.31 ,  0.067, 18.   ,  0.995]])

In [ ]:
regression_model = LogisticRegression(solver='lbfgs', max_iter=10000)
rfe = RFE(estimator=regression_model, n_features_to_select=3)

In [ ]:
rfe.fit(X, Y)

RFE(estimator=LogisticRegression(max_iter=10000), n_features_to_select=3)

In [ ]:
rfe.n_features_

3

In [ ]:
rfe.support_

array([False,  True, False, False,  True, False, False, False, False,
        True])

3 отобранных признака
* volatile acidity (летучая кислотность)
* chlorides (количество хлоридов)
* alcohol (крепкость)

In [ ]:
rfe.ranking_

array([5, 1, 4, 6, 1, 7, 8, 2, 3, 1])

Можно заметить, что на оценку также сильно влияют такие факторы как pH (кислотность) и sulphates (количество сульфатов)

In [ ]:
pca = PCA(n_components=3)
pca.fit(X)
pca.explained_variance_ratio_

array([0.954, 0.041, 0.005])

In [ ]:
pca.components_

array([[-7.409e-03, -1.184e-03,  4.869e-04,  4.102e-02, -1.682e-04,
         2.305e-01,  9.722e-01,  1.768e-06, -6.555e-04, -7.044e-04],
       [-5.360e-03, -7.839e-04, -2.481e-04,  1.866e-02,  6.755e-05,
         9.727e-01, -2.314e-01,  1.380e-06,  6.478e-04,  3.466e-04],
       [ 2.254e-02,  7.504e-04,  1.977e-03,  9.987e-01,  1.063e-04,
        -2.747e-02, -3.546e-02,  4.530e-04, -6.921e-03, -2.024e-03]])

Смысл алгоритма PCA - аппроксимация данных n-мерным элипсом в пространстве признаков. Полученные 3 вектора - оси, представляющие направления максимальной дисперсии данных

In [ ]:
pca.fit_transform(X)

array([[ 56.71 ,   1.809,  12.912],
       [ 11.844, -19.902,  -3.982],
       [-18.291,   3.85 ,   2.154],
       ...,
       [-74.112,  15.992,  -0.434],
       [-69.541,  17.981,  -0.968],
       [-74.647,   4.856,   1.09 ]])

In [ ]:
extra_trees_cls = ExtraTreesClassifier(n_estimators=100)
extra_trees_cls.fit(X, Y)
extra_trees_cls.feature_importances_

array([0.088, 0.111, 0.094, 0.097, 0.099, 0.096, 0.101, 0.122, 0.092,
       0.099])

Можно заметить, что наиболее информативны признаки volatile_acidity (летучая кислотность) и density (плотность)